# Generated by Django 4.2.1 on 2023-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img/%y')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('testimony', models.CharField(max_length=20000)),
            ],
        ),
    ]
