# Generated by Django 3.0.5 on 2023-11-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20231111_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
